name: "Test compiling against Java 8, 11 and 16"

on: {} # Solar - don't trigger at all
#  pull_request:
#    branches:
#    - development
#    paths:
#    - "src/**"
#    - "build.gradle"

jobs:
  testBuilds:
    name: "Test-compile against Java 8, 11 and 16"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java-version: [8, 11, 16]
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v2
    - name: "Prepare Java ${{ matrix.java-version }}"
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "${{ matrix.java-version }}"
    - name: "Make build.gradle executable"
      run: "chmod +x gradlew"
    - name: "Build jar with Java ${{ matrix.java-version }}"
      run: "./gradlew shadowJar"
